name: sphrs CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  HOST: x86_64-unknown-linux-gnu

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Test 
        run: cargo test --all --all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Clippy
        run: cargo +nightly clippy --all-targets --all-features -- -D warnings

  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: sphrs docs
        run: cargo rustdoc --all-features -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@beta
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
