name: Spellcheck
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    name: Spell Check with typos-cli
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Check spelling
      uses: crate-ci/typos@master